name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  my-job-new:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello Mahesh!"
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run JavaScript script
        run: node path/to/your/script.js
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install ESLint
        run: npm install eslint --save-dev
      - name: Run ESLint
        run: npx eslint
